apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "irsa-emu.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
