---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "irsa-emu.fullname" . }}-webhook-cert
  namespace: {{ .Release.Namespace }}
data:
  cert.pem: {{ tpl .Values.tls.cert . }}
  key.pem: {{ .Values.tls.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "irsa-emu.fullname" . }}-aws-envvars
  namespace: {{ .Release.Namespace }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.sidecar.awsAccessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.sidecar.awsSecretAccessKey }}
  AWS_DEFAULT_REGION: {{ .Values.sidecar.awsDefaultRegion }}
